#!/home/slate/SLATE/venv/bin/python3

#import os
import sys
from app.core.fph_hrns_maps import fph_to_hrns

if len(sys.argv) < 2:
    print("No FPH provided")
    sys.exit()
hrns = fph_to_hrns(sys.argv[1])
if hrns:
    print(hrns)
    sys.exit()
else:
    print("No HRNS found for FPH = " + sys.argv[1])
    sys.exit()
