#!/home/slate/SLATE/venv/bin/python3

import os
import sys
from app.core.common import nshash
from app.core.fph_hrns_maps import fph_to_hrns, hrns_to_fph
from app.core.slate_core import get_entity_types

script_name = sys.argv[0].replace(".py", "").replace("./", "")
script_name = script_name.replace("/usr/local/bin/", "")
script_name = script_name.replace("tools/", "")

#print(sys.argv[0])
#print(script_name)
#print(sys.argv[1])

def list_to_set_display(etypelist):
    etypeset = str(etypelist)
    etypeset = etypeset.replace("'", "")
    etypeset = etypeset.replace("[", "{")
    etypeset = etypeset.replace("]", "}")
    return etypeset

if script_name == "fph_to_hrns":
    fph = sys.argv[1]
    etypes, m = get_entity_types(fph)
    print(fph + " > " + fph_to_hrns(fph) + " \t", end="")
    print(list_to_set_display(etypes))
    if m:
        print(" (" + m + ")")
elif script_name == "hrns_to_fph":
    hrns = sys.argv[1]
    fph_1 = nshash(hrns)
    fph_2, m = hrns_to_fph(hrns)
    if fph_1 != fph_2:
        print("hash mismatch")
    if fph_to_hrns(fph_2) != hrns:
        print("HRNS>FPH inconsistent with FPH>HRNS")
    else:
        etypes, m = get_entity_types(fph_2)
        print(hrns + " > " + fph_2 + " \t", end="")
        print(list_to_set_display(etypes))
        if m:
            print(" (" + m + ")")
