#!/home/slate/SLATE/venv/bin/python3

#import os
import sys
from app.core.fph_hrns_maps import hrns_to_fph

if len(sys.argv) < 2:
    print("No HRNS provided so assumed empty string = SUBSTRATE")
    hrns = ""
else:
    hrns = sys.argv[1]
fph, m = hrns_to_fph(hrns)
if m:
    print(m)
else:
    print(fph)
