#!/home/slate/SLATE/venv/bin/python3

import sys
from prettytable import PrettyTable
from app.core.slate_core import identify_entity
from app.core.slate_core import get_primid_properties
from app.core.fph_hrns_maps import fph_to_hrns
from app.core.display import truefalse

entity_identifier = sys.argv[1] # identifier (FPH or HRNS)

identifier_fph, identifier_hrns, etypes, m = identify_entity(entity_identifier)

if not ("primid" in etypes):
    print("No primid: " + identifier_hrns + " (" + identifier_fph + ")")
    sys.exit(1)

# Fetch *primid* properties
active, administrator, ahids_fph_list, secids_fph_list, pmap, \
nstewardships_list, cstewardships_list, \
m = get_primid_properties(identifier_fph)
# set up table:
primid_table = PrettyTable()
primid_table.align = "l"
primid_table.field_names = ["property", "value(s)"]
table_rows = [] # one row per property
# identifier HRNS
table_row = []
table_row.append("identifier (FPH & HRNS)")
table_row.append(identifier_fph + " <> " + identifier_hrns)
table_rows.append(table_row)
# active?
table_row = []
table_row.append("active")
table_row.append(truefalse(active))
table_rows.append(table_row)
# administrator?
table_row = []
table_row.append("administrator")
table_row.append(truefalse(administrator))
table_rows.append(table_row)

primid_table.add_rows(table_rows[0:])
print(primid_table)

print("\npmap (pairing map)")
# set up table:
pmap_table = PrettyTable()
pmap_table.align = "l"
pmap_table.field_names = ["ahid", "currency", "account FPH", "account HRNS"]
table_rows = [] # one row per pairing
for ahid_hrns in pmap.keys():
    for currency_hrns in pmap[ahid_hrns].keys():
        table_row = []
        table_row.append(ahid_hrns)
        table_row.append(currency_hrns)
        table_row.append(pmap[ahid_hrns][currency_hrns])
        table_row.append(fph_to_hrns(pmap[ahid_hrns][currency_hrns]))
        table_rows.append(table_row)

pmap_table.add_rows(table_rows[0:])
print(pmap_table)
print()

# namespace stewardships:
print("namespace stewardships: ", end="")
if len(nstewardships_list) == 0:
    print("none\n")
else:
    print()
    for nstewardship_fph in nstewardships_list:
        print("  " + nstewardship_fph + " > " + fph_to_hrns(nstewardship_fph))
    print()

# currency stewardships:
print("currency stewardships: ", end="")
if len(cstewardships_list) == 0:
    print("none\n")
else:
    print()
    for cstewardship_fph in cstewardships_list:
        print("  " + cstewardship_fph + " > " + fph_to_hrns(cstewardship_fph))

# ahids:
print("\nahids: ", end="")
if len(ahids_fph_list) == 0:
    print("none\n")
else:
    print()
    for ahid_fph in ahids_fph_list:
        print("  " + ahid_fph + " > " + fph_to_hrns(ahid_fph))

# secids:
print("\nsecids: ", end="")
if len(secids_fph_list) == 0:
    print("none\n")
else:
    print()
    for secid_fph in secids_fph_list:
        print("  " + secid_fph + " > " + fph_to_hrns(secid_fph))

sys.exit(1)
