#!/home/slate/SLATE/venv/bin/python3

import random

import sys, os, re, argparse
import math
from faker import Faker
from prettytable import PrettyTable
from wonderwords import RandomWord

from app.core.fph_hrns_maps import fph_to_hrns, hrns_to_fph

from app.core.slate_core import new_namespace, new_currency, new_primid
from app.core.slate_core import split_hrns
from app.core.slate_core import identify_entity
from app.core.slate_core import new_pairing
from app.core.slate_core import retrieve_pmap
from app.core.slate_core import complete_parent_namespace
from app.core.payments import ah_payment

#==============================================================================
# Set command line options:

ap = argparse.ArgumentParser(description = "Create a random payment set")
ap.add_argument(
    "-p", "--primid", dest = "primid_id", action = "store",
    help = "Login identity of user"
)
ap.add_argument(
    "-n", "--number-of-payments", dest = "n_payments", action = "store",
    default = 100,
    help = "Number of payments"
)
ap.add_argument(
    "-c", "--currency", dest = "currency_id", action = "store",
    help = "Currency"
)
ap.add_argument(
    "-a", "--ahid-prefix", dest = "ahid_prefix",  action = "store",
    default = "a",
    help = "Prefix for AHID identifiers"
)
ap.add_argument(
    "-A", "--number-of-ahid", dest = "number_of_ahid",  action = "store",
    default = 10,
    help = "The number of AHIDs to be created"
)
ap.add_argument(
    "-u", "--use-names", dest = "use_names", action = "store_true",
    default = False,
    help = "Use named AHIDs instead of numbered AHIDs"
)
ap.add_argument(
    "-m", "--max-name-length", dest = "max_name_length", action = "store",
    default = 4,
    help = "Maximum length of AHIDs names"
)
ap.add_argument(
    "-G", "--gibberish", dest = "gibberish", action = "store_true",
    default = False,
    help = "Create utter gibberish in the annotations field"
)
args = ap.parse_args()

if args.primid_id is None:
    ap.print_help()
    sys.exit(1)
else:
    primid_id = args.primid_id

n_payments = int(args.n_payments)
currency_id = args.currency_id
ahid_prefix = args.ahid_prefix
number_of_ahid = int(args.number_of_ahid)
use_names = args.use_names
max_name_length = int(args.max_name_length)
gibberish = args.gibberish

if ahid_prefix.isalpha():
    ahid_prefix = ahid_prefix.lower()
else:
    sys.stderr.write("The AHID prefix must be alphabetic")
    sys.exit(1)

if use_names:
    # Initialize Faker object
    fake = Faker()
    Faker.seed(24)

print("Number of payments: " + str(n_payments))
print("Currency:           " + currency_id)
print("AHID prefix:        " + ahid_prefix)
print("Number of AHIDs:    " + str(number_of_ahid))
print("Usings names:       " + str(use_names))
zpad = math.ceil(math.log10(n_payments))
apad = math.ceil(math.log10(number_of_ahid))

primid_fph, primid_hrns, etypes, m = identify_entity(primid_id)
if not primid_fph:
    sys.stderr.write("Specified primid does not exist")
    sys.exit(1)

currency_fph, currency_hrns, etypes, m = identify_entity(currency_id)
if not currency_fph:
    sys.stderr.write("Specified currency does not exist")
    sys.exit(1)

print()

ahid_hrns_list = []
ahid_count = 0
while ahid_count < number_of_ahid:
    if use_names:
        name = "longrubbishname"
        while len(name) > max_name_length:
            name = fake.first_name()
            ahid_hrns = name.lower() + "." + primid_hrns
    else:
        ahid_hrns = ahid_prefix + str(i) + "." + primid_hrns
    if not (ahid_hrns in ahid_hrns_list):
        ahid_hrns_list.append(ahid_hrns)
        ahid_count += 1
        print(str(ahid_count).zfill(apad) + " : " + ahid_hrns)
print()
print("Number of unique AHID = " + str(len(list(set(ahid_hrns_list)))))

for ahid_hrns in ahid_hrns_list:
    p_fph, p_hrns, m = new_pairing(primid_id, ahid_hrns, currency_hrns)
    print(p_fph + ": pairing " + currency_hrns + " with " + ahid_hrns)

pmap, m = retrieve_pmap(primid_hrns)

display_random_selection = True
test_payments = True

print("="*80)
for n in range(n_payments):
    payer_ahid_hrns = random.choice(ahid_hrns_list)
    payee_ahid_hrns = random.choice(ahid_hrns_list)
    amount = random.randint(0, 100000)

    if gibberish:
        rword = RandomWord()
        rwords = rword.random_words(3) # list
        annotation = " ".join(rwords)
    else:
        annotation = "test" + str(n).zfill(4)

    if payer_ahid_hrns != payee_ahid_hrns:
        if display_random_selection:
            print(
                currency_hrns + " : " \
                + payer_ahid_hrns + " > " + payee_ahid_hrns \
                + " | " + str(amount) \
                + " | " + annotation
            )
        if test_payments:
            m = ah_payment(
                    payer_ahid_hrns,
                    payee_ahid_hrns,
                    currency_hrns,
                    amount,
                    annotation
                )
            if m:
                print(m)
print("="*80)
