#!/home/slate/SLATE/venv/bin/python3

import sqlite3
import sys
import os
import pickle
from prettytable import PrettyTable
from app.core.constants import ENTITIES_DB
from app.core.slate_core import get_entity_types
from app.core.slate_core import identify_entity
from app.core.slate_core import get_account_properties
from app.core.fph_hrns_maps import hrns_to_fph, fph_to_hrns
from app.core.display import integer_to_money_format
from app.core.display import integer_to_money_s_format
from app.core.display import truefalse

#script_name = sys.argv[0].replace(".py", "").replace("./", "")
#script_name = script_name.replace("/usr/local/bin/", "")
#script_name = script_name.replace("tools/", "")

entity_identifier = sys.argv[1] # identifier (FPH or HRNS)

identifier_fph, identifier_hrns, etypes, m = identify_entity(entity_identifier)

if not ("account" in etypes):
    print("No account: " + identifier_hrns + " (" + identifier_fph + ")")
    sys.exit(1)

# fetch *account* properties
currency_fph, \
owner_fph, \
ahid_fph, \
balance, \
volume, \
active, \
m = get_account_properties(identifier_fph)
# set up table:
account_table = PrettyTable()
account_table.align = "l"
account_table.field_names = ["property", "value(s)"]
table_rows = [] # one row per property
# identifier HRNS
table_row = []
table_row.append("HRNS")
table_row.append(identifier_hrns)
table_rows.append(table_row)
# identifier FPH
table_row = []
table_row.append("FPH")
table_row.append(identifier_fph)
table_rows.append(table_row)
# active?
table_row = []
table_row.append("active")
table_row.append(str(active))
table_rows.append(table_row)
# owner:
table_row = []
table_row.append("owner")
table_row.append(fph_to_hrns(owner_fph))
table_rows.append(table_row)
# ahid:
table_row = []
table_row.append("AHID")
table_row.append(fph_to_hrns(ahid_fph))
table_rows.append(table_row)
# balance:
table_row = []
table_row.append("balance")
table_row.append(integer_to_money_format(balance))
table_rows.append(table_row)
# volume:
table_row = []
table_row.append("volume")
table_row.append(integer_to_money_format(volume))
table_rows.append(table_row)

account_table.add_rows(table_rows[0:])
print(account_table)

sys.exit(1)
