#!/home/slate/SLATE/venv/bin/python3

import sys
import re

from app.core.slate_core import identify_entity, new_primid
from app.core.fph_hrns_maps import fph_to_hrns, hrns_to_fph
from app.core.regexp_list import re_realname, re_email, re_password, re_pin


#==============================================================================
# Bulk creation of *primids* from a CSV file with format:
#   name:parent namespace:real name:email1:email2:password:PIN
# e.g.
#   "fred":gc.chep.mon.uk":"":"fred@dodgy.com":"":"bAdpA55w0rd":"314159"
# Generally run over SSH as (e.g.):
#   cat <filename>.csv | ssh -p <port> <user>@<server> slate_import_primids
# where
#   filename.csv    is the name of the CSV file to be imported
#   user            is the SSH login name of a user with SLATE/NESTS access
#   port            is port number forwarded to a VM running SLATE/NESTS
# and  slate_import_primids  is this script, which sits somewhere easily
# found in the PATH (typically /usr/local/bin/).
#
# This script may only be run by a hub administrator.

#re_primid_csv_line = re.compile(r'^((\".*\":)|:){8}\".*\"$')


errors = []
primids_created = []
line_num = 0

for line in sys.stdin:
    print(line)
    if line.rstrip() == "q":
        sys.exit(1)
    if line == "":
        continue
    line_num += 1
    line_no = str(line_num).zfill(3)
    field = line.rstrip().split(",")
    if len(field) != 8:
        errors.append(line_no + ": ERROR: malformed input line")
        continue
    field = line.rstrip().split(",")
    primid_name = field[0].strip("\"")
    parent_ns = field[1].strip("\"")
    real_name = field[2].strip("\"")
    if real_name:
        if not re_realname.match(real_name):
            errors.append(
                       line_no + "ERROR: real name " + real_name \
                       + " is invalid so has been discarded"
                   )
            real_name = ""
    email1 = field[3].strip("\"")
    if email1:
        if not re_email.match(email1):
            errors.append(line_no + "ERROR: email1 invalid")
            continue
    email2 = field[4].strip("\"")
    if email2:
        if not re_email.match(email2):
           errors.append(line_no + "ERROR: email2 invalid - ignored")
           email2 = ""
    password = field[5].strip("\"")
    if password == "":
        errors.append(line_no + "ERROR: no password provided")
        continue
    pin = field[6].strip("\"")
    if pin == "":
        errors.append(line_no + "ERROR: no PIN provided")
        continue
    elif not re_pin.match(pin):
        errors.append(line_no + "ERROR: invalid PIN")
        continue
    currency_id = field[7].strip("\"")
    currency_fph, currency_hrns, etypes, \
    m = identify_entity(currency_id)
    if not ("currency" in etypes):
        errors.append(line_no + "ERROR: invalid currency")
        continue

    parent_namespace_fph, parent_namespace_hrns, etypes, \
    m = identify_entity(parent_ns)
    if m:
        errors.append(line_no + "ERROR: " + m)
        continue
    if parent_namespace_fph == "":
        errors.append(line_no + "ERROR: " + parent_ns + " is not an entity")
        continue
    elif not ("namespace" in etypes):
        errors.append(line_no + "ERROR: " + parent_ns + " has no namespace")
        continue

    primid_fph, primid_hrns, access_token, \
    m = new_primid(
            primid_name,
            parent_namespace_fph,
            real_name,
            email1,
            email2,
            password,
            pin,
            currency_fph
        )
    if m:
         errors.append(line_no + "ERROR: " + m)
    else:
        primids_created.append(
                               line_no + primid_fph + " > " + primid_hrns
                           )


print("\nLogin identities created:\n")
for primid in primids_created:
    print(primid)

print("\nErrors:\n")
for error in errors:
    print(error)
