#!/home/slate/SLATE/venv/bin/python3

import sys
import re

from app.core.slate_core import identify_entity, get_entity_type, new_currency
from app.core.fph_hrns_maps import fph_to_hrns, hrns_to_fph

#==============================================================================
# Bulk creation of *currencies* from a CSV file with format:
#   currency name:parent namespace:initial steward:P:S:default account name
# e.g.
#   "gc":"chep.mon.uk":"jw.chep.mon.uk":"":"h":"hrs"
# Generally run over SSH as (e.g.):
#   cat <filename>.csv | ssh -p <port> <user>@<server> slate_import_currencies
# where
#   filename.csv    is the name of the CSV file to be imported
#   user            is the SSH login name of a user with SLATE/NESTS access
#   port            is port number forwarded to a VM running SLATE/NESTS
# and  slate_import_currencies  is this script, which sits somewhere easily
# found in the PATH (typically /usr/local/bin/).

re_currency_csv_line = re.compile(r'^((\".*\":)|:){5}\".*\"$')

errors = []
currencies_created = []
line_number = 0

for line in sys.stdin:
    if line.rstrip() == "q":
        sys.exit(1)
    if line == "":
        continue
    line_number += 1
    line_no = str(line_number).zfill(3) + ": "
    if not re_currency_csv_line.match(line):
        errors.append(line_no + "ERROR: malformed input line")
        continue
    field = line.rstrip().split(":")
    currency_name = field[0].strip("\"")
    parent_ns = field[1].strip("\"")
    steward1 = field[2].strip("\"")
    prefix = field[3].strip("\"")
    suffix = field[4].strip("\"")
    default_account_name = field[5].strip("\"")

    parent_namespace_fph, parent_namespace_hrns, etypes, \
    m = identify_entity(parent_ns)
    if m:
        errors.append(line_no + "ERROR: " + m)
    if parent_namespace_fph == "":
        errors.append(line_no + "ERROR: " + currency_name + " is not an entity")
    elif not ("namespace" in etypes):
        errors.append(
            line_no + parent_ns + " is " + etype + " (not a namespace)"
        )

    steward_fph, steward_hrns, etypes, \
    m = identify_entity(steward1)
    if m:
        errors.append(line_no + "ERROR: " + m)
    if steward_fph == "":
        errors.append(line_no + "ERROR: " + steward1 + " is not an entity")
    elif not ("primid" in etypes):
        errors.append(
            line_no + "ERROR: " + steward1 + " is " + etype \
            + " (not a primary identity)"
        )

    currency_fph, currency_hrns, \
    m = new_currency(
            currency_name,
            parent_namespace_fph,
            steward_fph,
            prefix,
            suffix,
            default_account_name
          )
    if m:
         errors.append(line_no + "ERROR: " + m)
    else:
        currencies_created.append(
                               line_no + currency_fph + " > " + currency_hrns
                           )

print("\nNamespaces created:\n")
for currency in currencies_created:
    print(currency)

print("\nErrors:\n")
for error in errors:
    print(error)
