#!/home/slate/SLATE/venv/bin/python3

import sys
from prettytable import PrettyTable
from app.core.slate_core import identify_entity
from app.core.slate_core import get_namespace_properties
from app.core.fph_hrns_maps import fph_to_hrns
from app.core.display import truefalse

entity_identifier = sys.argv[1] # identifier (FPH or HRNS)

identifier_fph, identifier_hrns, etypes, m = identify_entity(entity_identifier)

if not ("namespace" in etypes):
    print("No namespace: " + identifier_hrns + " (" + identifier_fph + ")")
    sys.exit(1)

# fetch *namespace* properties
active, sandbox, private, owner_fph, currency_fph, stewards_list, \
m = get_namespace_properties(identifier_fph)
# set up table:
namespace_table = PrettyTable()
namespace_table.align = "l"
namespace_table.field_names = ["property", "value(s)"]
table_rows = [] # one row per property
# identifier HRNS
table_row = []
table_row.append("identifier (FPH & HRNS)")
table_row.append(identifier_fph + " <> " + identifier_hrns)
table_rows.append(table_row)
# active?
table_row = []
table_row.append("active")
table_row.append(truefalse(active))
table_rows.append(table_row)
# private?
table_row = []
table_row.append("private")
table_row.append(truefalse(private))
table_rows.append(table_row)
# owner (if private)
table_row = []
table_row.append("owner")
if private:
    table_row.append(fph_to_hrns(owner_fph))
else:
    table_row.append("none")
table_rows.append(table_row)
# default *currency*
table_row = []
table_row.append("default currency")
if currency_fph:
    table_row.append(fph_to_hrns(currency_fph))
else:
    table_row.append("none")
table_rows.append(table_row)

namespace_table.add_rows(table_rows[0:])
print(namespace_table)

# stewards:
print("\nstewards: ", end="")
if len(stewards_list) == 0:
    print("none")
else:
    print()
    for steward_fph in stewards_list:
        print("  " + steward_fph + " <> " + fph_to_hrns(steward_fph))
print()

sys.exit(1)
