#!/home/slate/SLATE/venv/bin/python3

# Create a new ad hoc root "namespace" and a *currency* sharing its identifier.

import sys
from app.core.slate_seed import create_root_namespace
from app.core.fph_hrns_maps import fph_to_hrns

steward_hrns = "cc" 

def show_help():
    print("New ad hoc root (namespace + currency) created:")
    print("    slate_create_root <name>")


if len(sys.argv) == 2:
    name = sys.argv[1]
    namespace_fph, namespace_hrns, m = create_root_namespace(name)
    if m:
        print(m)
        show_help()
    sys.exit()
else:
    show_help()
    sys.exit()



