#!/home/slate/SLATE/venv/bin/python3

import sys, os, re, argparse


from app.core.slate_core import identify_entity
from app.core.slate_core import get_currency_properties
from app.core.slate_core import get_namespace_properties
from app.core.slate_core import activate_currency, deactivate_currency
from app.core.slate_core import activate_namespace, deactivate_namespace
from app.core.slate_core import open_namespace, close_namespace
from app.core.slate_core import open_currency, close_currency
from app.core.slate_core import add_namespace_steward, remove_namespace_steward
from app.core.slate_core import add_currency_steward, remove_currency_steward
from app.core.slate_core import set_currency_parameter


#==============================================================================
# Set command line options:

ap = argparse.ArgumentParser(description = "Manage a namespace or currency")
ap.add_argument(
    "-a", "--auth-identity", dest = "auth_id", action = "store",
    help = "Login identity of a steward of this namespace or currency"
)
ap.add_argument(
    "-N", "--namespace", dest = "namespace_id", action = "store",
    help = "Operate on specified namespace"
)
ap.add_argument(
    "-C", "--currency", dest = "currency_id", action = "store",
    help = "Operate on specified currency"
)
ap.add_argument(
    "-e", "--enable", dest = "enable_entity", action = "store_true",
    help = "Enable namespace or currency"
)
ap.add_argument(
    "-d", "--disable", dest = "disable_entity", action = "store_true",
    help = "Disable namespace or currency"
)
ap.add_argument(
    "-s", "--suspend", dest = "disable_entity", action = "store_true",
    help = "Suspend namespace or currency"
)
ap.add_argument(
    "-o", "--open", dest = "open_entity", action = "store_true",
    help = "Open namespace or currency"
)
ap.add_argument(
    "-c", "--close", dest = "close_entity", action = "store_true",
    help = "Close namespace or currency"
)
ap.add_argument(
    "-S", "--add-steward", dest = "new_steward_id", action = "store",
    help = "Add steward"
)
ap.add_argument(
    "-R", "--remove-steward", dest = "removed_steward_id", action = "store",
    help = "Remove steward"
)
args = ap.parse_args()

# boolean
enable_entity = False
disable_entity = False
open_entity = False
close_entity = False
enable_entity = args.enable_entity
disable_entity = args.disable_entity
open_entity = args.open_entity
close_entity = args.close_entity

# First check that either a namespace or a currency is specified, but not both:
if args.namespace_id is not None:
    namespace_id = args.namespace_id
    entity_type = "namespace"
else:
    namespace_id = ""
if args.currency_id is not None:
    currency_id = args.currency_id
    entity_type = "currency"
else:
    currency_id = ""
if namespace_id and currency_id:
    sys.stderr.write("Namespace or currency - not both\n")
    ap.print_help()
    sys.exit(1)
elif not (namespace_id or currency_id):
    sys.stderr.write("Namespace or currency - specify\n")
    ap.print_help()
    sys.exit(1)

# The authorizing steward must be a primid:
if args.auth_id is not None:
    auth_id = args.auth_id
else:
    sys.stderr.write("No authorizing steward specified\n")
    ap.print_help()
    sys.exit(1)

auth_fph, auth_hrns, etypes, m = identify_entity(auth_id)
if not auth_fph:
    sys.stderr.write(auth_id + " is not a registered identifier\n")
    sys.exit(1)
if not ("primid" in etypes):
    sys.stderr.write(auth_hrns + " has no registered primid\n")
    sys.exit(1)

add_steward = False
remove_steward = False
if args.new_steward_id is not None:
    new_steward_id = args.new_steward_id
    add_steward = True
    steward_id = new_steward_id
if args.removed_steward_id:
    removed_steward_id = args.removed_steward_id
    remove_steward = True
    steward_id = removed_steward_id

# The added/removed steward is authenticated (must be a primid):
if add_steward or remove_steward:
    steward_fph, steward_hrns, etypes, m = identify_entity(steward_id)
    if not steward_fph:
        sys.stderr.write(steward_id + " is not a registered identifier\n")
        sys.exit(1)
    if not ("primid" in etypes):
        sys.stderr.write(steward_hrns + " has no registered primid\n")
        sys.exit(1)

# The entity type and authenticating steward are validated:
if entity_type == "currency":
    currency_fph, currency_hrns, etypes, m = identify_entity(currency_id)
    if not currency_fph:
        sys.stderr.write(currency_id + " is not a registered identifier\n")
        sys.exit(1)
    elif not (entity_type in etypes):
        sys.stderr.write(currency_hrns + " has no registered currency\n")
        sys.exit(1)
    currency_fph, currency_hrns, \
    active, open, private, sandbox, \
    currency_type, currency_category, currency_units, \
    currency_metrical_equivalence, currency_dimensions, \
    prefix, suffix, default_account_name, \
    stewards_list, m = get_currency_properties(currency_fph)
    if not (auth_fph in stewards_list):
        sys.stderr.write(
            auth_hrns + " not a steward of currency " + currency_hrns + "\n"
        )
        sys.exit(1)
    elif add_steward:
        m = add_currency_steward(currency_id, auth_id, steward_id)
        print(m)
        sys.exit(1)
    elif remove_steward:
        m = remove_currency_steward(currency_id, auth_id, steward_id)
        print(m)
        sys.exit(1)
    elif open_entity:
        open_currency(currency_id, auth_id)
        sys.exit(1)
    elif close_entity:
        close_currency(currency_id, auth_id)
        sys.exit(1)
    elif enable_entity:
        activate_currency(currency_id, auth_id)
        sys.exit(1)
    elif disable_entity:
        deactivate_currency(entity_id, auth_id)
        sys.exit(1)
    else:
        ap.print_help()
        sys.exit(1)
elif entity_type == "namespace":
    namespace_fph, namespace_hrns, etypes, m = identify_entity(namespace_id)
    if not namespace_fph:
        sys.stderr.write(namespace_id + " is not a registered identifier\n")
        sys.exit(1)
    elif not (entity_type in etypes):
        sys.stderr.write(namespace_hrns + " has no registered namespace\n")
        sys.exit(1)
    active, open, sandbox, private, owner_fph, \
    parent_currency_fph, stewards_list, \
    m = get_namespace_properties(namespace_fph)
    if not (auth_fph in stewards_list):
        sys.stderr.write(
            auth_hrns + " not a steward of namespace " + namespace_hrns + "\n"
        )
        sys.exit(1)
    elif add_steward:
        m = add_namespace_steward(namespace_id, auth_id, steward_id)
        print(m)
        sys.exit(1)
    elif remove_steward:
        m = remove_namespace_steward(namespace_id, auth_id, steward_id)
        print(m)
        sys.exit(1)
    elif open_entity:
        open_namespace(namespace_id, auth_id)
        sys.exit(1)
    elif close_entity:
        close_namespace(namespace_id, auth_id)
        sys.exit(1)
    elif enable_entity:
        activate_namespace(namespace_id, auth_id)
        sys.exit(1)
    elif disable_entity:
        deactivate_namespace(namespace_id, auth_id)
        sys.exit(1)
    else:
        ap.print_help()
        sys.exit(1)
else:
    sys.stderr.write("WTF?\n")
    sys.exit(1)
