#!/home/slate/SLATE/venv/bin/python3

import sqlite3
import sys
import os
import pickle
from prettytable import PrettyTable
from app.core.constants import ENTITIES_DB
from app.core.slate_core import get_entity_types
from app.core.slate_core import identify_entity
from app.core.slate_core import get_secid_properties
from app.core.fph_hrns_maps import hrns_to_fph, fph_to_hrns
from app.core.display import truefalse

#script_name = sys.argv[0].replace(".py", "").replace("./", "")
#script_name = script_name.replace("/usr/local/bin/", "")
#script_name = script_name.replace("tools/", "")

entity_identifier = sys.argv[1] # identifier (FPH or HRNS)

identifier_fph, identifier_hrns, etypes, m = identify_entity(entity_identifier)

if not ("secid" in etypes):
    print("No secid: " + identifier_hrns + " (" + identifier_fph + ")")
    sys.exit(1)

# fetch *secid* properties
active, \
primid_fph, \
accounts_list, \
m = get_secid_properties(identifier_fph)
# set up table:
secid_table = PrettyTable()
secid_table.align = "l"
secid_table.field_names = ["property", "value(s)"]
table_rows = [] # one row per property
# identifier HRNS
table_row = []
table_row.append("HRNS")
table_row.append(identifier_hrns)
table_rows.append(table_row)
# identifier FPH
table_row = []
table_row.append("FPH")
table_row.append(identifier_fph)
table_rows.append(table_row)
# active?
table_row = []
table_row.append("Active")
table_row.append(truefalse(active))
table_rows.append(table_row)
# owner (primid):
table_row = []
table_row.append("owner (primid)")
table_row.append(fph_to_hrns(primid_fph))
table_rows.append(table_row)
# accounts:
table_row = []
table_row.append("accounts")
accounts = []
for account_fph in accounts_list:
    accounts.append(fph_to_hrns(account_fph))
if len(accounts) > 0:
    table_row.append(", ".join(accounts))
else:
    table_row.append("none")
table_rows.append(table_row)

secid_table.add_rows(table_rows[0:])
print(secid_table)

sys.exit(1)
