#!/home/slate/SLATE/venv/bin/python3

import sys
from prettytable import PrettyTable
from app.core.slate_core import identify_entity
from app.core.slate_core import get_currency_properties
from app.core.slate_core import list_currency_accounts
from app.core.fph_hrns_maps import fph_to_hrns
from app.core.display import truefalse

if sys.argv[1] == "-A": # list *accounts*?
    list_accounts = True
    entity_identifier = sys.argv[2] # identifier (FPH or HRNS)
else:
    list_accounts = False
    entity_identifier = sys.argv[1] # identifier (FPH or HRNS)

identifier_fph, identifier_hrns, etypes, m = identify_entity(entity_identifier)
if not ("currency" in etypes):
    print("No currency: " + identifier_hrns + " (" + identifier_fph + ")")
    sys.exit(1)

# fetch *currency* properties
currency_fph, currency_hrns, \
active, open, private, sandbox, \
account_type, account_category, units, metrical_equivalence, dimensions, \
prefix, suffix, default_account_name, \
stewards_list, \
m = get_currency_properties(identifier_fph)
# set up table:
currency_table = PrettyTable()
currency_table.align = "l"
currency_table.field_names = ["property", "value(s)"]
table_rows = [] # one row per property
# identifier (FPH & HRNS)
table_row = []
table_row.append("identifier (FPH & HRNS)")
table_row.append(currency_fph + " = " + currency_hrns)
table_rows.append(table_row)
# active?
table_row = []
table_row.append("active")
table_row.append(truefalse(active))
table_rows.append(table_row)
# open?
table_row = []
table_row.append("open")
table_row.append(truefalse(active))
table_rows.append(table_row)
# private?
table_row = []
table_row.append("private")
table_row.append(truefalse(private))
table_rows.append(table_row)
# default *account* name:
table_row = []
table_row.append("default account name")
table_row.append(default_account_name)
table_rows.append(table_row)
# prefix:
table_row = []
table_row.append("prefix")
table_row.append(prefix)
table_rows.append(table_row)
# suffix:
table_row = []
table_row.append("suffix")
table_row.append(suffix)
table_rows.append(table_row)
# account_type:
table_row = []
table_row.append("account type")
table_row.append(account_type)
table_rows.append(table_row)
# category:
table_row = []
table_row.append("account category")
table_row.append(account_category)
table_rows.append(table_row)
# units:
table_row = []
table_row.append("units")
table_row.append(units)
table_rows.append(table_row)
# metrical_equivalence:
table_row = []
table_row.append("metrical equivalence")
table_row.append(metrical_equivalence)
table_rows.append(table_row)
# dimensions:
table_row = []
table_row.append("units")
table_row.append(units)
table_rows.append(table_row)

currency_table.add_rows(table_rows[0:])
print(currency_table)

# stewards:
print("\nstewards: ", end="")
if len(stewards_list) == 0:
    print("none")
else:
    print()
    for steward_fph in stewards_list:
        print("  " + steward_fph + " = " + fph_to_hrns(steward_fph))
print()

# *accounst*:
if list_accounts:
    print("\naccounts: ", end="")
    accounts_list = list_currency_accounts(currency_fph)
    if len(accounts_list) == 0:
        print("none")
    else:
        print()
        for account_fph in accounts_list:
            print("  " + account_fph + " = " + fph_to_hrns(account_fph))
    print()

sys.exit(1)
