#!/home/slate/SLATE/venv/bin/python3

import sys
from prettytable import PrettyTable
from app.core.slate_core import identify_entity
from app.core.slate_core import get_ahid_properties
from app.core.fph_hrns_maps import fph_to_hrns
from app.core.display import truefalse

if sys.argv[1] == "-A": # list *accounts*?
    list_accounts = True
    entity_identifier = sys.argv[2] # identifier (FPH or HRNS)
else:
    list_accounts = False
    entity_identifier = sys.argv[1] # identifier (FPH or HRNS)

identifier_fph, identifier_hrns, etypes, \
m = identify_entity(entity_identifier)
if not ("ahid" in etypes):
    print("No AHID: " + identifier_hrns + " (" + identifier_fph + ")")
    sys.exit(1)

# fetch *ahid* properties
active, primid_fph, accounts_fph_list, m = get_ahid_properties(identifier_fph)
# set up table:
ahid_table = PrettyTable()
ahid_table.align = "l"
ahid_table.field_names = ["property", "value(s)"]
table_rows = [] # one row per property
# identifier HRNS
table_row = []
table_row.append("identifier (FPH & HRNS)")
table_row.append(identifier_fph + " = " + identifier_hrns)
table_rows.append(table_row)
# owner
table_row = []
table_row.append("owner (primid)")
table_row.append(primid_fph + " = " + fph_to_hrns(primid_fph))
table_rows.append(table_row)
# active?
table_row = []
table_row.append("active")
table_row.append(truefalse(active))
table_rows.append(table_row)
ahid_table.add_rows(table_rows[0:])
print(ahid_table)

# *accounst*:
print("\naccounts: ", end="")
print(len(accounts_fph_list))
if list_accounts:
    for account_fph in accounts_fph_list:
        print("  " + account_fph + " = " + fph_to_hrns(account_fph))
print()

sys.exit(1)
