#!/home/slate/SLATE/venv/bin/python3

import sys
from prettytable import PrettyTable
from app.core.slate_core import identify_entity
from app.core.slate_core import get_account_properties
from app.core.fph_hrns_maps import fph_to_hrns
from app.core.display import integer_to_money_format
from app.core.display import integer_to_money_s_format
from app.core.display import truefalse

entity_identifier = sys.argv[1] # identifier (FPH or HRNS)

identifier_fph, identifier_hrns, etypes, m = identify_entity(entity_identifier)

if not ("account" in etypes):
    print("No account: " + identifier_hrns + " (" + identifier_fph + ")")
    sys.exit(1)

# fetch *account* properties
currency_fph, owner_fph, balance, volume, active, \
account_type, account_category, account_units, \
account_metrical_equivalence, account_dimensions, \
m = get_account_properties(identifier_fph)
# set up table:
account_table = PrettyTable()
account_table.align = "l"
account_table.field_names = ["property", "value(s)"]
table_rows = [] # one row per property
# identifier HRNS
table_row = []
table_row.append("identifier (FPH <> HRNS)")
table_row.append(identifier_fph + " = " + identifier_hrns)
table_rows.append(table_row)
# currency:
table_row = []
table_row.append("currency")
table_row.append(fph_to_hrns(currency_fph))
table_rows.append(table_row)
# balance:
table_row = []
table_row.append("balance")
table_row.append(integer_to_money_format(balance))
table_rows.append(table_row)
# volume:
table_row = []
table_row.append("volume")
table_row.append(integer_to_money_format(volume))
table_rows.append(table_row)
# active?
table_row = []
table_row.append("active")
table_row.append(truefalse(active))
table_rows.append(table_row)
# owner:
owner_fph, owner_hrns, etypes, m = identify_entity(owner_fph)
if ("ahid" in etypes):
    owner_type = "ahid"
elif ("secid" in etypes):
    owner_type = "secid"
table_row = []
table_row.append("owner (FPH <> HRNS)")
table_row.append(owner_fph + " = " + owner_hrns)
table_rows.append(table_row)
# owner type:
table_row = []
table_row.append("owner type")
table_row.append(owner_type)
table_rows.append(table_row)
# account type:
table_row = []
table_row.append("account type")
table_row.append(account_type)
table_rows.append(table_row)
# category:
table_row = []
table_row.append("account category")
table_row.append(account_category)
table_rows.append(table_row)
# account units:
table_row = []
table_row.append("account units")
table_row.append(account_units)
table_rows.append(table_row)
# metrical equivalence:
table_row = []
table_row.append("metrical equivalence")
table_row.append(account_metrical_equivalence)
table_rows.append(table_row)
# dimensions:
table_row = []
table_row.append("dimensions")
table_row.append(account_dimensions)
table_rows.append(table_row)

account_table.add_rows(table_rows[0:])
print(account_table)

sys.exit(1)
