#!/home/slate/SLATE/venv/bin/python3

import sys

from app.core.slate_core import identify_entity
from app.core.slate_core import get_currency_properties
from app.core.slate_core import get_namespace_properties
from app.core.slate_core import activate_currency, deactivate_currency
from app.core.slate_core import activate_namespace, deactivate_namespace
from app.core.slate_core import open_namespace, close_namespace
from app.core.slate_core import open_currency, close_currency
from app.core.slate_core import add_namespace_steward, remove_namespace_steward
from app.core.slate_core import add_currency_steward, remove_currency_steward

# Called as:
#   slate_manage_entity <auth_id> <type> <entity_id> <op> <auth_id>

def show_help():
    print(
        "slate_manage_entity <auth_id> <type> <entity_id> " \
        + "<operation> <auth_id>\n\n" \
        + "  auth_id:    HRNS or FPH of an existing steward of this entity\n" \
        + "  type:       namespace | currency\n" \
        + "  entity_id:  HRNS or FPH of the namespace or currency\n" \
        + "  operation:  enable | disable | open | close " \
        + " | add-steward | remove-steward\n" \
        + "  auth_id: HRNS or FPH of a steward to be added or removed"
    )

if (len(sys.argv) == 1) or (sys.argv[1] in ["h", "-h", "help", "--help"]):
    show_help()
    sys.exit(1)

auth_id = sys.argv[1]
auth_fph, auth_hrns, etypes, m = identify_entity(auth_id)
#print(auth_hrns)
if not auth_fph:
    print(auth_id + " is not a registered identifier")
    show_help()
    sys.exit(1)
elif not ("primid" in etypes):
    print("No primary identity " + auth_hrns)
    show_help()
    sys.exit(1)

entity_type = sys.argv[2]
#print(entity_type)
if not (entity_type in ["namespace", "currency"]):
    print("The second argument must be 'namespace' or 'currency'\n")
    show_help()
    sys.exit(1)

entity_id = sys.argv[3]
entity_fph, entity_hrns, etypes, m = identify_entity(entity_id)
#print(entity_hrns)
if not (entity_type in etypes):
    print("No " + entity_type + " at " + entity_hrns + " (" + entity_fph + ")")
    show_help()
    sys.exit(1)

ops = ["enable", "disable", "open", "close", "add-steward", "remove-steward"]
operation = sys.argv[4]
#print(operation)
if not (operation in ops):
    print(operation + " is not a valid operation\n")
    show_help()
    sys.exit(1)

if operation in ["add-steward", "remove-steward"]:
    steward_id = sys.argv[5]
    steward_fph, steward_hrns, etypes, \
    m = identify_entity(steward_id)
    if not ("primid" in etypes):
        print("No primary identifier" + steward_hrns)
        show_help()
        sys.exit(1)
#
if entity_type == "namespace":
    active, open, sandbox, private, stewards_list, \
    default_currency_fph, owner_fph, \
    m = get_namespace_properties(entity_id)
    if not (auth_fph in stewards_list):
        print(auth_hrns + " is not a steward of " + entity_hrns)
        show_help()
        sys.exit(1)
    elif operation == "add-steward":
        add_namespace_steward(entity_id, auth_id, steward_id)
        sys.exit(1)
    elif operation == "remove-steward":
        remove_namespace_steward(entity_id, auth_id, steward_id)
        sys.exit(1)
    elif operation == "open":
        open_namespace(entity_id, auth_id)
        sys.exit(1)
    elif operation == "close":
        close_namespace(entity_id, auth_id)
        sys.exit(1)
    elif operation == "enable":
        activate_namespace(entity_id, auth_id)
        sys.exit(1)
    elif operation == "disable":
        deactivate_namespace(entity_id, auth_id)
        sys.exit(1)
    else:
        sys.exit(1)
elif entity_type == "currency":
    currency_fph, currency_hrns, active, open, private, sandbox, \
    type, category, units, metrical_equivalence, dimensions, \
    prefix, suffix, default_account_name, stewards_list, \
    m = get_currency_properties(entity_id)
    if not (auth_fph in stewards_list):
        print(auth_hrns + " is not a steward of " + entity_hrns)
        show_help()
        sys.exit(1)
    elif operation == "add-steward":
        add_currency_steward(entity_id, auth_id, steward_id)
        sys.exit(1)
    elif operation == "remove-steward":
        remove_currency_steward(entity_id, auth_id, steward_id)
        sys.exit(1)
    elif operation == "open":
        open_namespace(entity_id, auth_id)
        sys.exit(1)
    elif operation == "close":
        close_namespace(entity_id, auth_id)
        sys.exit(1)
    elif operation == "enable":
        activate_namespace(entity_id, auth_id)
        sys.exit(1)
    elif operation == "disable":
        deactivate_namespace(entity_id, auth_id)
        sys.exit(1)
    else:
        sys.exit(1)
