#!/home/slate/SLATE/venv/bin/python3

import sys
import sqlite3
#from prettytable import PrettyTable
from app.core.constants import MAP_DB
from app.core.fph_hrns_maps import hrns_to_fph, fph_to_hrns

show_mappings = False
if len(sys.argv) > 1:
    if sys.argv[1] == "l":
        show_mappings = True

print()
fph_hrns_d = {}
hrns_fph_d = {}
with sqlite3.connect(MAP_DB) as conn:
    cursor = conn.cursor()
#    s = "HRNS > FPH reverse mapping check"
#    print(s + " " + "="*(79 - len(s)) + "\n")
    cursor.execute("SELECT fph, hrns FROM fph_hrns_map")
    result = cursor.fetchall()
    if result is None:
        print("No FPH>HRNS mapping listed")
        cursor.close()
        sys.exit()
    fph_hrns_mapping_list = result
    n_fph_hrns_mappings = len(fph_hrns_mapping_list)
    print(str(n_fph_hrns_mappings) + " FPH > HRNS mappings found")
    for fph_hrns_mapping in fph_hrns_mapping_list:
        fph_hrns_d[fph_hrns_mapping[0]] = fph_hrns_mapping[1]
    if show_mappings:
        print()
        for fph in fph_hrns_d.keys():
            print(fph + " > " + fph_hrns_d[fph])
        print()
    fph_duplicates = []
    fph_clean_list = []
    for fph in fph_hrns_d.keys():
        if fph not in fph_clean_list:
            fph_clean_list.append(fph)
        else:
            fph_duplicates.append(fph)
    if len(fph_duplicates) == 0:
        print("No FPH duplicates found")
    else:
        print("FPH duplicates found:")
        for fph in fph_duplicates:
            print(fph)
    fph_list = fph_clean_list # no duplicates
    hrns_fph_omissions = []
    for fph in fph_hrns_d.keys():
        hrns = fph_hrns_d[fph]
        cursor.execute("SELECT fph FROM hrns_fph_map WHERE hrns = ?", (hrns,))
        result = cursor.fetchone()
        if result is None:
            print(fph + " > " + hrns + " has no reverse mapping")
            hrns_fph_omissions.append(fph + " > " + hrns)
    if len(hrns_fph_omissions) == 0:
        print("No HRNS>FPH omissions found")
    else:
        for hrns_fph_omission in hrns_fph_omissions:
            print(hrns_fph_omission)
#    print()
#    s = "HRNS > FPH reverse mapping check"
#    print(s + " " + "="*(79 - len(s)) + "\n")
    cursor.execute("SELECT hrns, fph FROM hrns_fph_map")
    result = cursor.fetchall()
    if result is None:
        print("No HRNS>FPH mapping listed")
        cursor.close()
        sys.exit()
    else:
        hrns_fph_mapping_list = result
    n_hrns_fph_mappings = len(hrns_fph_mapping_list)
    print(str(n_hrns_fph_mappings) + " HRNS > FPH mappings found")
    if n_hrns_fph_mappings != n_fph_hrns_mappings:
        print("Mapping tables length mismatch found")
    else:
        print("Mapping tables match in length")
    for hrns_fph_mapping in hrns_fph_mapping_list:
        hrns_fph_d[hrns_fph_mapping[0]] = hrns_fph_mapping[1]
    if show_mappings:
        print()
        for hrns in hrns_fph_d.keys():
            print(hrns + " > " + hrns_fph_d[hrns])
        print()
    hrns_duplicates = []
    hrns_clean_list = []
    for hrns in hrns_fph_d.keys():
        if hrns not in hrns_clean_list:
            hrns_clean_list.append(hrns)
        else:
            hrns_duplicates.append(hrns)
    if len(hrns_duplicates) == 0:
        print("No HRNS duplicates found")
    else:
        print("HRNS duplicates found:")
        for hrns in hrns_duplicates:
            print(hrns)
    fph_hrns_omissions = []
    for hrns in hrns_fph_d.keys():
        cursor.execute("SELECT hrns FROM fph_hrns_map WHERE fph = ?", (fph,))
        result = cursor.fetchone()
        if result is None:
            print(hrns + " > " + fph + " has no reverse mapping")
            fph_hrns_omissions.append(hrns + " > " + fph)
    if len(fph_hrns_omissions) == 0:
        print("No FPH>HRNS omissions")
    else:
        for fph_hrns_omission in fph_hrns_omissions:
            print(fph_hrns_omission)
    print()
    cursor.close()
