#!/home/slate/SLATE/venv/bin/python3

from prettytable import PrettyTable

from app.core.configdb import create_config_map
from app.core.configdb import get_config
#from app.core.configdb import delete_config_key_from_map
#from app.core.configdb import set_config
from app.core.configdb import read_config_file_to_map
from app.core.dbm_functions import dbm_keys
from app.core.constants import CONFIG_MAP



# The hub configuration map is populated from the ~/hub_config file.
create_config_map()
errors = read_config_file_to_map()
if errors:
    print(errors)

# The configuration values are displayed:
#for k in dbm_keys(CONFIG_MAP):
#    print(k + " : " + str(get_config(k)))
#print()

config_table = PrettyTable()
config_table.align = "l"
config_table.field_names = ["label", "value"]
table_rows = []
keys_sorted = []
for k in dbm_keys(CONFIG_MAP):
    keys_sorted.append(k)
keys_sorted.sort()
for k in keys_sorted:
    table_row = []
    table_row.append(k)
    config_value = str(get_config(k))
    if config_value in ["False", "True"]:
        config_value = config_value.lower()
#    table_row.append(str(get_config(k)))
    table_row.append(config_value)
    table_rows.append(table_row)
config_table.add_rows(table_rows[0:])
print(config_table)
