#!/home/slate/SLATE/venv/bin/python3

import sqlite3
import sys
import os
import pickle
from prettytable import PrettyTable
from app.core.constants import ENTITIES_DB
from app.core.slate_core import get_entity_types
from app.core.slate_core import identify_entity
from app.core.slate_core import get_ahid_properties
from app.core.fph_hrns_maps import hrns_to_fph, fph_to_hrns
from app.core.display import truefalse

script_name = sys.argv[0].replace(".py", "").replace("./", "")
script_name = script_name.replace("/usr/local/bin/", "")
script_name = script_name.replace("tools/", "")

entity_identifier = sys.argv[1] # identifier (FPH or HRNS)

identifier_fph, identifier_hrns, etypes, m = identify_entity(entity_identifier)

if not ("ahid" in etypes):
    print("No AHID: " + identifier_hrns + " (" + identifier_fph + ")")
    sys.exit(1)

# fetch *ahid* properties
active, \
primid_fph, \
accounts_fph_list, \
m = get_ahid_properties(identifier_fph)
# set up table:
ahid_table = PrettyTable()
ahid_table.align = "l"
ahid_table.field_names = ["property", "value(s)"]
table_rows = [] # one row per property
# identifier HRNS
table_row = []
table_row.append("HRNS")
table_row.append(identifier_hrns)
table_rows.append(table_row)
# identifier FPH
table_row = []
table_row.append("FPH")
table_row.append(identifier_fph)
table_rows.append(table_row)
# active?
table_row = []
table_row.append("active")
table_row.append(truefalse(active))
table_rows.append(table_row)
# accounts:
table_row = []
table_row.append("accounts")
accounts_fph_list = []
for account_fph in accounts_fph_list:
    accounts_fph_list.append(fph_to_hrns(account_fph))
table_row.append(", ".join(accounts_fph_list))
table_rows.append(table_row)

ahid_table.add_rows(table_rows[0:])
print(ahid_table)

sys.exit(1)
