

# Latin character ccTLD list
# (see https://en.wikipedia.org/wiki/Country_code_top-level_domain)

cctld_list = [ # used in: seed.py
    "ac", "ad", "ae", "af", "ag", "ai", "al", "am", "ao", "aq", "ar", "as",
    "at", "au", "aw", "ax", "az", "ba", "bb", "bd", "be", "bf", "bg", "bh", 
    "bi", "bj", "bm", "bn", "bo", "bq", "br", "bs", "bt", "bw", "by", "bz",
    "ca", "cc", "cd", "cf", "cg", "ch", "ci", "ck", "cl", "cm", "cn", "co",
    "cr", "cu", "cv", "cw", "cx", "cy", "cz", "de", "dj", "dk", "dm", "do",
    "dz", "ec", "ee", "eg", "eh", "er", "es", "et", "eu", "fi", "fj", "fk", 
    "fm", "fo", "fr", "ga", "gd", "ge", "gf", "gg", "gh", "gi", "gl", "gm",
    "gn", "gp", "gq", "gr", "gs", "gt", "gu", "gw", "gy", "hk", "hm", "hn", 
    "hr", "ht", "hu", "id", "ie", "il", "im", "in", "io", "iq", "ir", "is",
    "it", "je", "jm", "jo", "jp", "ke", "kg", "kh", "ki", "km", "kn", "kp", 
    "kr", "kw", "ky", "kz", "la", "lb", "lc", "li", "lk", "lr", "ls", "lt",
    "lu", "lv", "ly", "ma", "mc", "md", "me", "mg", "mh", "mk", "ml", "mm", 
    "mn", "mo", "mp", "mq", "mr", "ms", "mt", "mu", "mv", "mw", "mx", "my",
    "mz", "na", "nc", "ne", "nf", "ng", "ni", "nl", "no", "np", "nr", "nu", 
    "nz", "om", "pa", "pe", "pf", "pg", "ph", "pk", "pl", "pm", "pn", "pr",
    "ps", "pt", "pw", "py", "qa", "re", "ro", "rs", "ru", "rw", "sa", "sb", 
    "sc", "sd", "se", "sg", "sh", "si", "sk", "sl", "sm", "sn", "so", "sr",
    "ss", "st", "su", "sv", "sx", "sy", "sz", "tc", "td", "tf", "tg", "th", 
    "tj", "tk", "tl", "tm", "tn", "to", "tr", "tt", "tv", "tw", "tz", "ua",
    "ug", "uk", "us", "uy", "uz", "va", "vc", "ve", "vg", "vi", "vn", "vu", 
    "wf", "ws", "ye", "yt", "za", "zm", "zw" 
]

cctld_set = set(cctld_list)



cctld_list2 = { # used in: seed.py
    "ac" : "Ascension Island (United Kingdom)", 
    "ad" : "Andorra", 
    "ae" : "United Arab Emirates", 
    "af" : "Afghanistan", 
    "ag" : "Antigua and Barbuda", 
    "ai" : "Anguilla (United Kingdom)", 
    "al" : "Albania", 
    "am" : "Armenia", 
    "ao" : "Angola", 
    "aq" : "Antarctica", 
    "ar" : "Argentina", 
    "as" : "American Samoa (United States)", 
    "at" : "Austria", 
    "au" : "Australia", 
    "aw" : "Aruba (Kingdom of the Netherlands)", 
    "ax" : "Åland (Finland)", 
    "az" : "Azerbaijan", 
    "ba" : "Bosnia and Herzegovina", 
    "bb" : "Barbados", 
    "bd" : "Bangladesh", 
    "be" : "Belgium", 
    "bf" : "Burkina Faso", 
    "bg" : "Bulgaria", 
    "bh" : "Bahrain", 
    "bi" : "Burundi", 
    "bj" : "Benin", 
    "bm" : "Bermuda (United Kingdom)", 
    "bn" : "Brunei", 
    "bo" : "Bolivia", 
    "bq" : "Caribbean Netherlands (Bonaire, Saba and Saint Eustatius)", 
    "br" : "Brazil", 
    "bs" : "Bahamas", 
    "bt" : "Bhutan", 
    "bw" : "Botswana", 
    "by" : "Belarus", 
    "bz" : "Belize", 
    "ca" : "Canada", 
    "cc" : "Cocos (Keeling) Islands", 
    "cd" : "Democratic Republic of the Congo", 
    "cf" : "Central African Republic", 
    "cg" : "Republic of the Congo", 
    "ch" : "Switzerland", 
    "ci" : "Ivory Coast", 
    "ck" : "Cook Islands", 
    "cl" : "Chile", 
    "cm" : "Cameroon", 
    "cn" : "People's Republic of China", 
    "co" : "Colombia", 
    "cr" : "Costa Rica", 
    "cu" : "Cuba", 
    "cv" : "Cape Verde", 
    "cw" : "Curaçao (Kingdom of the Netherlands)", 
    "cx" : "Christmas Island", 
    "cy" : "Cyprus", 
    "cz" : "Czech Republic", 
    "de" : "Germany", 
    "dj" : "Djibouti", 
    "dk" : "Denmark", 
    "dm" : "Dominica", 
    "do" : "Dominican Republic", 
    "dz" : "Algeria", 
    "ec" : "Ecuador", 
    "ee" : "Estonia", 
    "eg" : "Egypt", 
    "eh" : "Western Sahara", 
    "er" : "Eritrea", 
    "es" : "Spain", 
    "et" : "Ethiopia", 
    "eu" : "European Union", 
    "fi" : "Finland", 
    "fj" : "Fiji", 
    "fk" : "Falkland Islands (United Kingdom)", 
    "fm" : "Federated States of Micronesia", 
    "fo" : "Faroe Islands (Kingdom of Denmark)", 
    "fr" : "France", 
    "ga" : "Gabon", 
    "gd" : "Grenada", 
    "ge" : "Georgia", 
    "gf" : "French Guiana (France)", 
    "gg" : "Guernsey", 
    "gh" : "Ghana", 
    "gi" : "Gibraltar (United Kingdom)", 
    "gl" : "Greenland (Kingdom of Denmark)", 
    "gm" : "The Gambia", 
    "gn" : "Guinea", 
    "gp" : "Guadeloupe (France)", 
    "gq" : "Equatorial Guinea", 
    "gr" : "Greece", 
    "gs" : "South Georgia and the South Sandwich Islands (United Kingdom)", 
    "gt" : "Guatemala", 
    "gu" : "Guam (United States)", 
    "gw" : "Guinea-Bissau", 
    "gy" : "Guyana", 
    "hk" : "Hong Kong", 
    "hm" : "Heard Island and McDonald Islands", 
    "hn" : "Honduras", 
    "hr" : "Croatia", 
    "ht" : "Haiti", 
    "hu" : "Hungary", 
    "id" : "Indonesia", 
    "ie" : "Ireland", 
    "il" : "Israel", 
    "im" : "Isle of Man", 
    "in" : "India", 
    "io" : "British Indian Ocean Territory (United Kingdom)", 
    "iq" : "Iraq", 
    "ir" : "Iran", 
    "is" : "Iceland", 
    "it" : "Italy", 
    "je" : "Jersey", 
    "jm" : "Jamaica", 
    "jo" : "Jordan", 
    "jp" : "Japan", 
    "ke" : "Kenya", 
    "kg" : "Kyrgyzstan", 
    "kh" : "Cambodia", 
    "ki" : "Kiribati", 
    "km" : "Comoros", 
    "kn" : "Saint Kitts and Nevis", 
    "kp" : "North Korea", 
    "kr" : "South Korea", 
    "kw" : "Kuwait", 
    "ky" : "Cayman Islands (United Kingdom)", 
    "kz" : "Kazakhstan", 
    "la" : "Laos", 
    "lb" : "Lebanon", 
    "lc" : "Saint Lucia", 
    "li" : "Liechtenstein", 
    "lk" : "Sri Lanka", 
    "lr" : "Liberia", 
    "ls" : "Lesotho", 
    "lt" : "Lithuania", 
    "lu" : "Luxembourg", 
    "lv" : "Latvia", 
    "ly" : "Libya", 
    "ma" : "Morocco", 
    "mc" : "Monaco", 
    "md" : "Moldova", 
    "me" : "Montenegro", 
    "mg" : "Madagascar", 
    "mh" : "Marshall Islands", 
    "mk" : "North Macedonia", 
    "ml" : "Mali", 
    "mm" : "Myanmar", 
    "mn" : "Mongolia", 
    "mo" : "Macau", 
    "mp" : "Northern Mariana Islands (United States)", 
    "mq" : "Martinique (France)", 
    "mr" : "Mauritania", 
    "ms" : "Montserrat (United Kingdom)", 
    "mt" : "Malta", 
    "mu" : "Mauritius", 
    "mv" : "Maldives", 
    "mw" : "Malawi", 
    "mx" : "Mexico", 
    "my" : "Malaysia", 
    "mz" : "Mozambique", 
    "na" : "Namibia", 
    "nc" : "New Caledonia (France)", 
    "ne" : "Niger", 
    "nf" : "Norfolk Island", 
    "ng" : "Nigeria", 
    "ni" : "Nicaragua", 
    "nl" : "Netherlands", 
    "no" : "Norway", 
    "np" : "Nepal", 
    "nr" : "Nauru", 
    "nu" : "Niue", 
    "nz" : "New Zealand", 
    "om" : "Oman", 
    "pa" : "Panama", 
    "pe" : "Peru", 
    "pf" : "French Polynesia (France)", 
    "pg" : "Papua New Guinea", 
    "ph" : "Philippines", 
    "pk" : "Pakistan", 
    "pl" : "Poland", 
    "pm" : "Saint-Pierre and Miquelon (France)", 
    "pn" : "Pitcairn Islands (United Kingdom)", 
    "pr" : "Puerto Rico (United States)", 
    "ps" : "Palestine[53]", 
    "pt" : "Portugal", 
    "pw" : "Palau", 
    "py" : "Paraguay", 
    "qa" : "Qatar", 
    "re" : "Réunion (France)", 
    "ro" : "Romania", 
    "rs" : "Serbia", 
    "ru" : "Russia", 
    "rw" : "Rwanda", 
    "sa" : "Saudi Arabia", 
    "sb" : "Solomon Islands", 
    "sc" : "Seychelles", 
    "sd" : "Sudan", 
    "se" : "Sweden", 
    "sg" : "Singapore", 
    "sh" : "Saint Helena, Ascension and Tristan da Cunha (United Kingdom)", 
    "si" : "Slovenia", 
    "sk" : "Slovakia", 
    "sl" : "Sierra Leone", 
    "sm" : "San Marino", 
    "sn" : "Senegal", 
    "so" : "Somalia", 
    "sr" : "Suriname", 
    "ss" : "South Sudan", 
    "st" : "São Tomé and Príncipe", 
    "su" : "Soviet Union", 
    "sv" : "El Salvador", 
    "sx" : "Sint Maarten (Kingdom of the Netherlands)", 
    "sy" : "Syria", 
    "sz" : "Eswatini", 
    "tc" : "Turks and Caicos Islands (United Kingdom)", 
    "td" : "Chad", 
    "tf" : "French Southern and Antarctic Lands", 
    "tg" : "Togo", 
    "th" : "Thailand", 
    "tj" : "Tajikistan", 
    "tk" : "Tokelau", 
    "tl" : "East Timor", 
    "tm" : "Turkmenistan", 
    "tn" : "Tunisia", 
    "to" : "Tonga", 
    "tr" : "Turkey", 
    "tt" : "Trinidad and Tobago", 
    "tv" : "Tuvalu", 
    "tw" : "Taiwan", 
    "tz" : "Tanzania", 
    "ua" : "Ukraine", 
    "ug" : "Uganda", 
    "uk" : "United Kingdom", 
    "us" : "United States of America", 
    "uy" : "Uruguay", 
    "uz" : "Uzbekistan", 
    "va" : "Vatican City", 
    "vc" : "Saint Vincent and the Grenadines", 
    "ve" : "Venezuela", 
    "vg" : "British Virgin Islands (United Kingdom)", 
    "vi" : "United States Virgin Islands (United States)", 
    "vn" : "Vietnam", 
    "vu" : "Vanuatu", 
    "wf" : "Wallis and Futuna", 
    "ws" : "Samoa", 
    "ye" : "Yemen", 
    "yt" : "Mayotte", 
    "za" : "South Africa", 
    "zm" : "Zambia", 
    "zw" : "Zimbabwe"
}

cctld_set2 = set(cctld_list2.keys())
